// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package databaseSQL

import (
	"database/sql"
)

type Balance struct {
	ID          int64          `json:"id"`
	StatementID sql.NullInt64  `json:"statement_id"`
	Name        interface{}    `json:"name"`
	Description sql.NullString `json:"description"`
	BalanceType interface{}    `json:"balance_type"`
	Value       float64        `json:"value"`
}

type Bank struct {
	ID          int64       `json:"id"`
	Name        interface{} `json:"name"`
	AccountID   interface{} `json:"account_id"`
	AccountType interface{} `json:"account_type"`
	FID         interface{} `json:"f_id"`
	BankID      interface{} `json:"bank_id"`
	BranchID    interface{} `json:"branch_id"`
}

type Card struct {
	ID        int64       `json:"id"`
	AccountID interface{} `json:"account_id"`
	Name      interface{} `json:"name"`
	FID       interface{} `json:"f_id"`
}

type Source struct {
	ID     int64       `json:"id"`
	CardID interface{} `json:"card_id"`
	BankID interface{} `json:"bank_id"`
}

type Statement struct {
	ID            int64         `json:"id"`
	SourceID      sql.NullInt64 `json:"source_id"`
	StartDate     interface{}   `json:"start_date"`
	EndDate       interface{}   `json:"end_date"`
	LedgerBalance float64       `json:"ledger_balance"`
	BalanceDate   interface{}   `json:"balance_date"`
	ServerDate    interface{}   `json:"server_date"`
	Language      interface{}   `json:"language"`
}

type Transaction struct {
	ID       interface{} `json:"id"`
	SourceID int64       `json:"source_id"`
	Date     interface{} `json:"date"`
	Value    float64     `json:"value"`
	Type     interface{} `json:"type"`
	Desc     string      `json:"desc"`
}
